spring.application.name=booknest-platform
# --- Spring Mail Configuration (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=utkarshmishra8871@gmail.com
# NOTE: This must be a 16-digit Google "App Password", not your normal login password!
spring.mail.password=mqlf ttpc jafs gnem
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true